[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.idea
  | \.pytest_cache
  | \.github
  | _build
  | build
  | dist
  | venv
  | test/resources
)/
'''
