# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12", "3.13"]
        include:
          - os: macos-latest
            python-version: '3.13'
          - os: windows-latest
            python-version: '3.13'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls flake8 setuptools wheel twine
        pip install -r requirements-test.txt --upgrade
        pip install black==24.10.0

    - name: Verify Code with Black
      run: |
        black --check puremagic test

    - name: Lint with flake8
      run: |
        # stop the tests if there are linting errors
        flake8 puremagic --count --show-source --statistics

    - name: Test with pytest
      run: |
        python -m pytest --cov=puremagic test/

    - name: Check distribution log description
      shell: bash
      run: |
        python setup.py sdist bdist_wheel
        twine check dist/*
        ls -lah "dist/"
        WHL=$(find dist -name *.whl -print -quit)
        echo ${WHL}
