# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12", "3.13"]
        include:
          - os: macos-latest
            python-version: '3.13'
          - os: windows-latest
            python-version: '3.13'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true
        cache: 'pip'

    - name: Install the latest version of uv and activate the environment
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true

    - name: Install dependencies
      run: uv sync --frozen

    - name: Verify Code with Ruff
      run: uv run ruff check

    - name: Test with pytest
      run: uv run pytest --cov=puremagic test/

    - name: Check distribution log description
      shell: bash
      run: |
        uv build
        twine check dist/*
        ls -lah "dist/"
        WHL=$(find dist -name *.whl -print -quit)
        echo ${WHL}
